/* oscars6ClientLib.c
   Generated by gSOAP 2.8.1 from oscars6API.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

/** Use this file in your project build instead of the two files oscars6C.c and oscars6Client.c. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "oscars6C.c"
#include "oscars6Client.c"

/* End of oscars6ClientLib.c */
