/* mntrH.h
   Generated by gSOAP 2.7.9l from mntr.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef mntrH_H
#define mntrH_H
#include "mntrStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE___ns1__status_USCOREpath
#define SOAP_TYPE___ns1__status_USCOREpath (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__status_USCOREpath(struct soap*, struct __ns1__status_USCOREpath *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__status_USCOREpath(struct soap*, const struct __ns1__status_USCOREpath *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__status_USCOREpath(struct soap*, const struct __ns1__status_USCOREpath *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__status_USCOREpath(struct soap*, const char*, int, const struct __ns1__status_USCOREpath *, const char*);
SOAP_FMAC3 struct __ns1__status_USCOREpath * SOAP_FMAC4 soap_get___ns1__status_USCOREpath(struct soap*, struct __ns1__status_USCOREpath *, const char*, const char*);
SOAP_FMAC3 struct __ns1__status_USCOREpath * SOAP_FMAC4 soap_in___ns1__status_USCOREpath(struct soap*, const char*, struct __ns1__status_USCOREpath *, const char*);

#ifndef SOAP_TYPE___ns1__remove_USCOREpath
#define SOAP_TYPE___ns1__remove_USCOREpath (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__remove_USCOREpath(struct soap*, struct __ns1__remove_USCOREpath *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__remove_USCOREpath(struct soap*, const struct __ns1__remove_USCOREpath *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__remove_USCOREpath(struct soap*, const struct __ns1__remove_USCOREpath *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__remove_USCOREpath(struct soap*, const char*, int, const struct __ns1__remove_USCOREpath *, const char*);
SOAP_FMAC3 struct __ns1__remove_USCOREpath * SOAP_FMAC4 soap_get___ns1__remove_USCOREpath(struct soap*, struct __ns1__remove_USCOREpath *, const char*, const char*);
SOAP_FMAC3 struct __ns1__remove_USCOREpath * SOAP_FMAC4 soap_in___ns1__remove_USCOREpath(struct soap*, const char*, struct __ns1__remove_USCOREpath *, const char*);

#ifndef SOAP_TYPE___ns1__new_USCOREpath
#define SOAP_TYPE___ns1__new_USCOREpath (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__new_USCOREpath(struct soap*, struct __ns1__new_USCOREpath *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__new_USCOREpath(struct soap*, const struct __ns1__new_USCOREpath *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__new_USCOREpath(struct soap*, const struct __ns1__new_USCOREpath *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__new_USCOREpath(struct soap*, const char*, int, const struct __ns1__new_USCOREpath *, const char*);
SOAP_FMAC3 struct __ns1__new_USCOREpath * SOAP_FMAC4 soap_get___ns1__new_USCOREpath(struct soap*, struct __ns1__new_USCOREpath *, const char*, const char*);
SOAP_FMAC3 struct __ns1__new_USCOREpath * SOAP_FMAC4 soap_in___ns1__new_USCOREpath(struct soap*, const char*, struct __ns1__new_USCOREpath *, const char*);

#ifndef SOAP_TYPE_ns1__remove_USCOREpath
#define SOAP_TYPE_ns1__remove_USCOREpath (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__remove_USCOREpath(struct soap*, struct ns1__remove_USCOREpath *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__remove_USCOREpath(struct soap*, const struct ns1__remove_USCOREpath *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__remove_USCOREpath(struct soap*, const struct ns1__remove_USCOREpath *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__remove_USCOREpath(struct soap*, const char*, int, const struct ns1__remove_USCOREpath *, const char*);
SOAP_FMAC3 struct ns1__remove_USCOREpath * SOAP_FMAC4 soap_get_ns1__remove_USCOREpath(struct soap*, struct ns1__remove_USCOREpath *, const char*, const char*);
SOAP_FMAC3 struct ns1__remove_USCOREpath * SOAP_FMAC4 soap_in_ns1__remove_USCOREpath(struct soap*, const char*, struct ns1__remove_USCOREpath *, const char*);

#ifndef SOAP_TYPE_ns1__new_USCOREpathResponse
#define SOAP_TYPE_ns1__new_USCOREpathResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__new_USCOREpathResponse(struct soap*, struct ns1__new_USCOREpathResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__new_USCOREpathResponse(struct soap*, const struct ns1__new_USCOREpathResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__new_USCOREpathResponse(struct soap*, const struct ns1__new_USCOREpathResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__new_USCOREpathResponse(struct soap*, const char*, int, const struct ns1__new_USCOREpathResponse *, const char*);
SOAP_FMAC3 struct ns1__new_USCOREpathResponse * SOAP_FMAC4 soap_get_ns1__new_USCOREpathResponse(struct soap*, struct ns1__new_USCOREpathResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__new_USCOREpathResponse * SOAP_FMAC4 soap_in_ns1__new_USCOREpathResponse(struct soap*, const char*, struct ns1__new_USCOREpathResponse *, const char*);

#ifndef SOAP_TYPE_ns1__status_USCOREpath
#define SOAP_TYPE_ns1__status_USCOREpath (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__status_USCOREpath(struct soap*, struct ns1__status_USCOREpath *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__status_USCOREpath(struct soap*, const struct ns1__status_USCOREpath *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__status_USCOREpath(struct soap*, const struct ns1__status_USCOREpath *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__status_USCOREpath(struct soap*, const char*, int, const struct ns1__status_USCOREpath *, const char*);
SOAP_FMAC3 struct ns1__status_USCOREpath * SOAP_FMAC4 soap_get_ns1__status_USCOREpath(struct soap*, struct ns1__status_USCOREpath *, const char*, const char*);
SOAP_FMAC3 struct ns1__status_USCOREpath * SOAP_FMAC4 soap_in_ns1__status_USCOREpath(struct soap*, const char*, struct ns1__status_USCOREpath *, const char*);

#ifndef SOAP_TYPE_ns1__status_USCOREpathResponse
#define SOAP_TYPE_ns1__status_USCOREpathResponse (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__status_USCOREpathResponse(struct soap*, struct ns1__status_USCOREpathResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__status_USCOREpathResponse(struct soap*, const struct ns1__status_USCOREpathResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__status_USCOREpathResponse(struct soap*, const struct ns1__status_USCOREpathResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__status_USCOREpathResponse(struct soap*, const char*, int, const struct ns1__status_USCOREpathResponse *, const char*);
SOAP_FMAC3 struct ns1__status_USCOREpathResponse * SOAP_FMAC4 soap_get_ns1__status_USCOREpathResponse(struct soap*, struct ns1__status_USCOREpathResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__status_USCOREpathResponse * SOAP_FMAC4 soap_in_ns1__status_USCOREpathResponse(struct soap*, const char*, struct ns1__status_USCOREpathResponse *, const char*);

#ifndef SOAP_TYPE_ns1__PathData
#define SOAP_TYPE_ns1__PathData (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__PathData(struct soap*, struct ns1__PathData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__PathData(struct soap*, const struct ns1__PathData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__PathData(struct soap*, const struct ns1__PathData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__PathData(struct soap*, const char*, int, const struct ns1__PathData *, const char*);
SOAP_FMAC3 struct ns1__PathData * SOAP_FMAC4 soap_get_ns1__PathData(struct soap*, struct ns1__PathData *, const char*, const char*);
SOAP_FMAC3 struct ns1__PathData * SOAP_FMAC4 soap_in_ns1__PathData(struct soap*, const char*, struct ns1__PathData *, const char*);

#ifndef SOAP_TYPE_ns1__new_USCOREpath
#define SOAP_TYPE_ns1__new_USCOREpath (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__new_USCOREpath(struct soap*, struct ns1__new_USCOREpath *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__new_USCOREpath(struct soap*, const struct ns1__new_USCOREpath *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__new_USCOREpath(struct soap*, const struct ns1__new_USCOREpath *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__new_USCOREpath(struct soap*, const char*, int, const struct ns1__new_USCOREpath *, const char*);
SOAP_FMAC3 struct ns1__new_USCOREpath * SOAP_FMAC4 soap_get_ns1__new_USCOREpath(struct soap*, struct ns1__new_USCOREpath *, const char*, const char*);
SOAP_FMAC3 struct ns1__new_USCOREpath * SOAP_FMAC4 soap_in_ns1__new_USCOREpath(struct soap*, const char*, struct ns1__new_USCOREpath *, const char*);

#ifndef SOAP_TYPE_ns1__remove_USCOREpathResponse
#define SOAP_TYPE_ns1__remove_USCOREpathResponse (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__remove_USCOREpathResponse(struct soap*, struct ns1__remove_USCOREpathResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__remove_USCOREpathResponse(struct soap*, const struct ns1__remove_USCOREpathResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__remove_USCOREpathResponse(struct soap*, const struct ns1__remove_USCOREpathResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__remove_USCOREpathResponse(struct soap*, const char*, int, const struct ns1__remove_USCOREpathResponse *, const char*);
SOAP_FMAC3 struct ns1__remove_USCOREpathResponse * SOAP_FMAC4 soap_get_ns1__remove_USCOREpathResponse(struct soap*, struct ns1__remove_USCOREpathResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__remove_USCOREpathResponse * SOAP_FMAC4 soap_in_ns1__remove_USCOREpathResponse(struct soap*, const char*, struct ns1__remove_USCOREpathResponse *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons1__status_USCOREpathResponse
#define SOAP_TYPE_PointerTons1__status_USCOREpathResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__status_USCOREpathResponse(struct soap*, struct ns1__status_USCOREpathResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__status_USCOREpathResponse(struct soap*, struct ns1__status_USCOREpathResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__status_USCOREpathResponse(struct soap*, const char *, int, struct ns1__status_USCOREpathResponse *const*, const char *);
SOAP_FMAC3 struct ns1__status_USCOREpathResponse ** SOAP_FMAC4 soap_get_PointerTons1__status_USCOREpathResponse(struct soap*, struct ns1__status_USCOREpathResponse **, const char*, const char*);
SOAP_FMAC3 struct ns1__status_USCOREpathResponse ** SOAP_FMAC4 soap_in_PointerTons1__status_USCOREpathResponse(struct soap*, const char*, struct ns1__status_USCOREpathResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__status_USCOREpath
#define SOAP_TYPE_PointerTons1__status_USCOREpath (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__status_USCOREpath(struct soap*, struct ns1__status_USCOREpath *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__status_USCOREpath(struct soap*, struct ns1__status_USCOREpath *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__status_USCOREpath(struct soap*, const char *, int, struct ns1__status_USCOREpath *const*, const char *);
SOAP_FMAC3 struct ns1__status_USCOREpath ** SOAP_FMAC4 soap_get_PointerTons1__status_USCOREpath(struct soap*, struct ns1__status_USCOREpath **, const char*, const char*);
SOAP_FMAC3 struct ns1__status_USCOREpath ** SOAP_FMAC4 soap_in_PointerTons1__status_USCOREpath(struct soap*, const char*, struct ns1__status_USCOREpath **, const char*);

#ifndef SOAP_TYPE_PointerTons1__remove_USCOREpathResponse
#define SOAP_TYPE_PointerTons1__remove_USCOREpathResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__remove_USCOREpathResponse(struct soap*, struct ns1__remove_USCOREpathResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__remove_USCOREpathResponse(struct soap*, struct ns1__remove_USCOREpathResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__remove_USCOREpathResponse(struct soap*, const char *, int, struct ns1__remove_USCOREpathResponse *const*, const char *);
SOAP_FMAC3 struct ns1__remove_USCOREpathResponse ** SOAP_FMAC4 soap_get_PointerTons1__remove_USCOREpathResponse(struct soap*, struct ns1__remove_USCOREpathResponse **, const char*, const char*);
SOAP_FMAC3 struct ns1__remove_USCOREpathResponse ** SOAP_FMAC4 soap_in_PointerTons1__remove_USCOREpathResponse(struct soap*, const char*, struct ns1__remove_USCOREpathResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__remove_USCOREpath
#define SOAP_TYPE_PointerTons1__remove_USCOREpath (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__remove_USCOREpath(struct soap*, struct ns1__remove_USCOREpath *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__remove_USCOREpath(struct soap*, struct ns1__remove_USCOREpath *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__remove_USCOREpath(struct soap*, const char *, int, struct ns1__remove_USCOREpath *const*, const char *);
SOAP_FMAC3 struct ns1__remove_USCOREpath ** SOAP_FMAC4 soap_get_PointerTons1__remove_USCOREpath(struct soap*, struct ns1__remove_USCOREpath **, const char*, const char*);
SOAP_FMAC3 struct ns1__remove_USCOREpath ** SOAP_FMAC4 soap_in_PointerTons1__remove_USCOREpath(struct soap*, const char*, struct ns1__remove_USCOREpath **, const char*);

#ifndef SOAP_TYPE_PointerTons1__new_USCOREpathResponse
#define SOAP_TYPE_PointerTons1__new_USCOREpathResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__new_USCOREpathResponse(struct soap*, struct ns1__new_USCOREpathResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__new_USCOREpathResponse(struct soap*, struct ns1__new_USCOREpathResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__new_USCOREpathResponse(struct soap*, const char *, int, struct ns1__new_USCOREpathResponse *const*, const char *);
SOAP_FMAC3 struct ns1__new_USCOREpathResponse ** SOAP_FMAC4 soap_get_PointerTons1__new_USCOREpathResponse(struct soap*, struct ns1__new_USCOREpathResponse **, const char*, const char*);
SOAP_FMAC3 struct ns1__new_USCOREpathResponse ** SOAP_FMAC4 soap_in_PointerTons1__new_USCOREpathResponse(struct soap*, const char*, struct ns1__new_USCOREpathResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__new_USCOREpath
#define SOAP_TYPE_PointerTons1__new_USCOREpath (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__new_USCOREpath(struct soap*, struct ns1__new_USCOREpath *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__new_USCOREpath(struct soap*, struct ns1__new_USCOREpath *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__new_USCOREpath(struct soap*, const char *, int, struct ns1__new_USCOREpath *const*, const char *);
SOAP_FMAC3 struct ns1__new_USCOREpath ** SOAP_FMAC4 soap_get_PointerTons1__new_USCOREpath(struct soap*, struct ns1__new_USCOREpath **, const char*, const char*);
SOAP_FMAC3 struct ns1__new_USCOREpath ** SOAP_FMAC4 soap_in_PointerTons1__new_USCOREpath(struct soap*, const char*, struct ns1__new_USCOREpath **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerTons1__PathData
#define SOAP_TYPE_PointerTons1__PathData (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__PathData(struct soap*, struct ns1__PathData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__PathData(struct soap*, struct ns1__PathData *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__PathData(struct soap*, const char *, int, struct ns1__PathData *const*, const char *);
SOAP_FMAC3 struct ns1__PathData ** SOAP_FMAC4 soap_get_PointerTons1__PathData(struct soap*, struct ns1__PathData **, const char*, const char*);
SOAP_FMAC3 struct ns1__PathData ** SOAP_FMAC4 soap_in_PointerTons1__PathData(struct soap*, const char*, struct ns1__PathData **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of mntrH.h */
