CC= gcc
INCLUDES= -I. -I../../libgsoap
LIBS= -lssl -lcrypto -lgsoap
LDFLAGS= -L../../libgsoap
CFLAGS= -DWITH_NONAMESPACES -DWITH_OPENSSL -DWITH_DOM

ALL= oscars_client
SRC= dom.c smdevp.c mecevp.c wsaapi.c wsseapi.c oscarsClient.c oscarsC.c oscars.c oscars_client.c
OBJS= ${SRC:.c=.o}

all: $(OBJS) $(ALL)

clean:
	rm -f $(ALL) $(OBJS) *.o

oscars_client: $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) $(LIBS) -o $@

.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $^
