/* oscarsStub.h
   Generated by gSOAP 2.8.1 from oscarsAPI.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef oscarsStub_H
#define oscarsStub_H
#define SOAP_WSA_2005
#define SOAP_NAMESPACE_OF_ns1	"http://oscars.es.net/OSCARS"
#define SOAP_NAMESPACE_OF_ns2	""
#define SOAP_NAMESPACE_OF_ns2	""
#define SOAP_NAMESPACE_OF_ns3	"http://ogf.org/schema/network/topology/ctrlPlane/20080828/"
#define SOAP_NAMESPACE_OF_ns4	"http://docs.oasis-open.org/wsn/b-2"
#define SOAP_NAMESPACE_OF_ns5	"http://docs.oasis-open.org/wsrf/r-2"
#define SOAP_NAMESPACE_OF_ns6	"http://docs.oasis-open.org/wsrf/bf-2"
#ifndef WITH_NONAMESPACES
#define WITH_NONAMESPACES
#endif
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_wsa5__RelationshipType
#define SOAP_TYPE_wsa5__RelationshipType (14)
/* wsa5:RelationshipType */
enum wsa5__RelationshipType {http_x003a_x002f_x002fwww_x002ew3_x002eorg_x002f2005_x002f08_x002faddressing_x002freply = 0};
typedef enum wsa5__RelationshipType wsa5__RelationshipType;
#endif

#ifndef SOAP_TYPE_wsa5__FaultCodesType
#define SOAP_TYPE_wsa5__FaultCodesType (15)
/* wsa5:FaultCodesType */
enum wsa5__FaultCodesType {wsa5__InvalidAddressingHeader = 0, wsa5__InvalidAddress = 1, wsa5__InvalidEPR = 2, wsa5__InvalidCardinality = 3, wsa5__MissingAddressInEPR = 4, wsa5__DuplicateMessageID = 5, wsa5__ActionMismatch = 6, wsa5__MessageAddressingHeaderRequired = 7, wsa5__DestinationUnreachable = 8, wsa5__ActionNotSupported = 9, wsa5__EndpointUnavailable = 10};
typedef enum wsa5__FaultCodesType wsa5__FaultCodesType;
#endif

#ifndef SOAP_TYPE__wsa5__IsReferenceParameter
#define SOAP_TYPE__wsa5__IsReferenceParameter (34)
/* wsa5:IsReferenceParameter */
enum _wsa5__IsReferenceParameter {wsa5__false = 0, wsa5__true = 1};
typedef enum _wsa5__IsReferenceParameter _wsa5__IsReferenceParameter;
#endif

#ifndef SOAP_TYPE_xsd__boolean_
#define SOAP_TYPE_xsd__boolean_ (40)
/* xsd:boolean */
enum xsd__boolean_ {_false = 0, _true = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_wsa5__EndpointReferenceType
#define SOAP_TYPE_wsa5__EndpointReferenceType (7)
/* wsa5:EndpointReferenceType */
struct wsa5__EndpointReferenceType
{
	char *Address;	/* required element of type xsd:string */
	struct wsa5__ReferenceParametersType *ReferenceParameters;	/* optional element of type wsa5:ReferenceParametersType */
	struct wsa5__MetadataType *Metadata;	/* optional element of type wsa5:MetadataType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
	char *__anyAttribute;	/* optional attribute of type xsd:anyType */
};
typedef struct wsa5__EndpointReferenceType wsa5__EndpointReferenceType;
#endif

#ifndef SOAP_TYPE_wsa5__ReferenceParametersType
#define SOAP_TYPE_wsa5__ReferenceParametersType (8)
/* wsa5:ReferenceParametersType */
struct wsa5__ReferenceParametersType
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
	char *__anyAttribute;	/* optional attribute of type xsd:anyType */
};
typedef struct wsa5__ReferenceParametersType wsa5__ReferenceParametersType;
#endif

#ifndef SOAP_TYPE_wsa5__MetadataType
#define SOAP_TYPE_wsa5__MetadataType (9)
/* wsa5:MetadataType */
struct wsa5__MetadataType
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
	char *__anyAttribute;	/* optional attribute of type xsd:anyType */
};
typedef struct wsa5__MetadataType wsa5__MetadataType;
#endif

#ifndef SOAP_TYPE_wsa5__ProblemActionType
#define SOAP_TYPE_wsa5__ProblemActionType (11)
/* wsa5:ProblemActionType */
struct wsa5__ProblemActionType
{
	char *Action;	/* optional element of type xsd:string */
	char *SoapAction;	/* optional element of type xsd:string */
	char *__anyAttribute;	/* optional attribute of type xsd:anyType */
};
typedef struct wsa5__ProblemActionType wsa5__ProblemActionType;
#endif

#ifndef SOAP_TYPE_wsa5__RelatesToType
#define SOAP_TYPE_wsa5__RelatesToType (10)
/* Primitive wsa5:RelatesToType schema type: */
struct wsa5__RelatesToType
{
	char *__item;
	char *RelationshipType;	/* optional attribute of type wsa5:RelationshipTypeOpenEnum */
	char *__anyAttribute;	/* optional attribute of type xsd:anyType */
};
typedef struct wsa5__RelatesToType wsa5__RelatesToType;
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (35)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	char *wsa5__MessageID;	/* optional element of type wsa5:MessageID */
	struct wsa5__RelatesToType *wsa5__RelatesTo;	/* optional element of type wsa5:RelatesTo */
	struct wsa5__EndpointReferenceType *wsa5__From;	/* optional element of type wsa5:From */
	struct wsa5__EndpointReferenceType *wsa5__ReplyTo;	/* mustUnderstand */
	struct wsa5__EndpointReferenceType *wsa5__FaultTo;	/* mustUnderstand */
	char *wsa5__To;	/* mustUnderstand */
	char *wsa5__Action;	/* mustUnderstand */
};
#endif

#endif

#ifndef SOAP_TYPE_ns1__resCreateContent
#define SOAP_TYPE_ns1__resCreateContent (42)
/* ns1:resCreateContent */
struct ns1__resCreateContent
{
	char *globalReservationId;	/* optional element of type xsd:string */
	LONG64 startTime;	/* required element of type xsd:long */
	LONG64 endTime;	/* required element of type xsd:long */
	int bandwidth;	/* required element of type xsd:int */
	char *description;	/* required element of type xsd:string */
	struct ns1__pathInfo *pathInfo;	/* required element of type ns1:pathInfo */
};
#endif

#ifndef SOAP_TYPE_ns1__createReply
#define SOAP_TYPE_ns1__createReply (46)
/* ns1:createReply */
struct ns1__createReply
{
	char *globalReservationId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	char *token;	/* optional element of type xsd:string */
	char *status;	/* required element of type xsd:string */
	struct ns1__pathInfo *pathInfo;	/* optional element of type ns1:pathInfo */
};
#endif

#ifndef SOAP_TYPE_ns1__modifyResContent
#define SOAP_TYPE_ns1__modifyResContent (47)
/* ns1:modifyResContent */
struct ns1__modifyResContent
{
	char *globalReservationId;	/* required element of type xsd:string */
	LONG64 startTime;	/* required element of type xsd:long */
	LONG64 endTime;	/* required element of type xsd:long */
	int bandwidth;	/* required element of type xsd:int */
	char *description;	/* required element of type xsd:string */
	struct ns1__pathInfo *pathInfo;	/* optional element of type ns1:pathInfo */
};
#endif

#ifndef SOAP_TYPE_ns1__modifyResReply
#define SOAP_TYPE_ns1__modifyResReply (48)
/* ns1:modifyResReply */
struct ns1__modifyResReply
{
	struct ns1__resDetails *reservation;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:resDetails */
};
#endif

#ifndef SOAP_TYPE_ns1__getTopologyContent
#define SOAP_TYPE_ns1__getTopologyContent (51)
/* ns1:getTopologyContent */
struct ns1__getTopologyContent
{
	char *topologyType;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getTopologyResponseContent
#define SOAP_TYPE_ns1__getTopologyResponseContent (52)
/* ns1:getTopologyResponseContent */
struct ns1__getTopologyResponseContent
{
	struct ns3__CtrlPlaneTopologyContent *ns3__topology;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns3:CtrlPlaneTopologyContent */
};
#endif

#ifndef SOAP_TYPE_ns1__createPathContent
#define SOAP_TYPE_ns1__createPathContent (55)
/* ns1:createPathContent */
struct ns1__createPathContent
{
	char *token;	/* optional element of type xsd:string */
	char *globalReservationId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__createPathResponseContent
#define SOAP_TYPE_ns1__createPathResponseContent (56)
/* ns1:createPathResponseContent */
struct ns1__createPathResponseContent
{
	char *globalReservationId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	char *status;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__refreshPathContent
#define SOAP_TYPE_ns1__refreshPathContent (57)
/* ns1:refreshPathContent */
struct ns1__refreshPathContent
{
	char *token;	/* optional element of type xsd:string */
	char *globalReservationId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__refreshPathResponseContent
#define SOAP_TYPE_ns1__refreshPathResponseContent (58)
/* ns1:refreshPathResponseContent */
struct ns1__refreshPathResponseContent
{
	char *globalReservationId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	char *status;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__teardownPathContent
#define SOAP_TYPE_ns1__teardownPathContent (59)
/* ns1:teardownPathContent */
struct ns1__teardownPathContent
{
	char *token;	/* optional element of type xsd:string */
	char *globalReservationId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__teardownPathResponseContent
#define SOAP_TYPE_ns1__teardownPathResponseContent (60)
/* ns1:teardownPathResponseContent */
struct ns1__teardownPathResponseContent
{
	char *globalReservationId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	char *status;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__resDetails
#define SOAP_TYPE_ns1__resDetails (49)
/* ns1:resDetails */
struct ns1__resDetails
{
	char *globalReservationId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	char *login;	/* required element of type xsd:string */
	char *status;	/* required element of type xsd:string */
	LONG64 startTime;	/* required element of type xsd:long */
	LONG64 endTime;	/* required element of type xsd:long */
	LONG64 createTime;	/* required element of type xsd:long */
	int bandwidth;	/* required element of type xsd:int */
	char *description;	/* required element of type xsd:string */
	struct ns1__pathInfo *pathInfo;	/* required element of type ns1:pathInfo */
};
#endif

#ifndef SOAP_TYPE___ns1__listRequest_sequence
#define SOAP_TYPE___ns1__listRequest_sequence (63)
/* Operation wrapper: */
struct __ns1__listRequest_sequence
{
	LONG64 startTime;	/* required element of type xsd:long */
	LONG64 endTime;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns1__listRequest
#define SOAP_TYPE_ns1__listRequest (61)
/* ns1:listRequest */
struct ns1__listRequest
{
	int __sizeresStatus;	/* sequence of 0 to 5 elements <resStatus> */
	char **resStatus;	/* sequence of 0 to 5 elements of type xsd:string */
	int __size_listRequest_sequence;	/* sequence of elements <-listRequest-sequence> */
	struct __ns1__listRequest_sequence *__listRequest_sequence;
	char *description;	/* optional element of type xsd:string */
	int __sizelinkId;	/* sequence of elements <linkId> */
	char **linkId;	/* optional element of type xsd:string */
	int __sizevlanTag;	/* sequence of elements <vlanTag> */
	struct ns1__vlanTag *vlanTag;	/* optional element of type ns1:vlanTag */
	int *resRequested;	/* optional element of type xsd:int */
	int *resOffset;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__listReply
#define SOAP_TYPE_ns1__listReply (68)
/* ns1:listReply */
struct ns1__listReply
{
	int __sizeresDetails;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <resDetails> */
	struct ns1__resDetails *resDetails;	/* optional element of type ns1:resDetails */
	int *totalResults;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__forwardPayload
#define SOAP_TYPE_ns1__forwardPayload (69)
/* ns1:forwardPayload */
struct ns1__forwardPayload
{
	char *contentType;	/* required element of type xsd:string */
	struct ns1__resCreateContent *createReservation;	/* optional element of type ns1:resCreateContent */
	struct ns1__modifyResContent *modifyReservation;	/* optional element of type ns1:modifyResContent */
	struct ns1__globalReservationId *cancelReservation;	/* optional element of type ns1:globalReservationId */
	struct ns1__globalReservationId *queryReservation;	/* optional element of type ns1:globalReservationId */
	struct ns1__listRequest *listReservations;	/* optional element of type ns1:listRequest */
	struct ns1__createPathContent *createPath;	/* optional element of type ns1:createPathContent */
	struct ns1__refreshPathContent *refreshPath;	/* optional element of type ns1:refreshPathContent */
	struct ns1__teardownPathContent *teardownPath;	/* optional element of type ns1:teardownPathContent */
};
#endif

#ifndef SOAP_TYPE_ns1__forwardReply
#define SOAP_TYPE_ns1__forwardReply (78)
/* ns1:forwardReply */
struct ns1__forwardReply
{
	char *contentType;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	struct ns1__createReply *createReservation;	/* optional element of type ns1:createReply */
	struct ns1__modifyResReply *modifyReservation;	/* optional element of type ns1:modifyResReply */
	char *cancelReservation;	/* optional element of type xsd:string */
	struct ns1__resDetails *queryReservation;	/* optional element of type ns1:resDetails */
	struct ns1__listReply *listReservations;	/* optional element of type ns1:listReply */
	struct ns1__createPathResponseContent *createPath;	/* optional element of type ns1:createPathResponseContent */
	struct ns1__refreshPathResponseContent *refreshPath;	/* optional element of type ns1:refreshPathResponseContent */
	struct ns1__teardownPathResponseContent *teardownPath;	/* optional element of type ns1:teardownPathResponseContent */
};
#endif

#ifndef SOAP_TYPE_ns1__pathInfo
#define SOAP_TYPE_ns1__pathInfo (44)
/* ns1:pathInfo */
struct ns1__pathInfo
{
	char *pathSetupMode;	/* required element of type xsd:string */
	char *pathType;	/* optional element of type xsd:string */
	struct ns3__CtrlPlanePathContent *path;	/* optional element of type ns3:CtrlPlanePathContent */
	struct ns1__layer2Info *layer2Info;	/* optional element of type ns1:layer2Info */
	struct ns1__layer3Info *layer3Info;	/* optional element of type ns1:layer3Info */
	struct ns1__mplsInfo *mplsInfo;	/* optional element of type ns1:mplsInfo */
};
#endif

#ifndef SOAP_TYPE_ns1__layer2Info
#define SOAP_TYPE_ns1__layer2Info (87)
/* ns1:layer2Info */
struct ns1__layer2Info
{
	struct ns1__vlanTag *srcVtag;	/* optional element of type ns1:vlanTag */
	struct ns1__vlanTag *destVtag;	/* optional element of type ns1:vlanTag */
	char *srcEndpoint;	/* required element of type xsd:string */
	char *destEndpoint;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__layer3Info
#define SOAP_TYPE_ns1__layer3Info (89)
/* ns1:layer3Info */
struct ns1__layer3Info
{
	char *srcHost;	/* required element of type xsd:string */
	char *destHost;	/* required element of type xsd:string */
	char *protocol;	/* optional element of type xsd:string */
	int *srcIpPort;	/* optional element of type xsd:int */
	int *destIpPort;	/* optional element of type xsd:int */
	char *dscp;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mplsInfo
#define SOAP_TYPE_ns1__mplsInfo (91)
/* ns1:mplsInfo */
struct ns1__mplsInfo
{
	int burstLimit;	/* required element of type xsd:int */
	char *lspClass;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__eventContent
#define SOAP_TYPE_ns1__eventContent (93)
/* ns1:eventContent */
struct ns1__eventContent
{
	char *type;	/* required element of type xsd:string */
	LONG64 timestamp;	/* required element of type xsd:long */
	char *userLogin;	/* optional element of type xsd:string */
	char *errorSource;	/* optional element of type xsd:string */
	char *errorCode;	/* optional element of type xsd:string */
	char *errorMessage;	/* optional element of type xsd:string */
	struct ns1__resDetails *resDetails;	/* optional element of type ns1:resDetails */
	struct ns1__msgDetails *msgDetails;	/* optional element of type ns1:msgDetails */
	struct ns1__localDetails *localDetails;	/* optional element of type ns1:localDetails */
	char *id;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__localDetails
#define SOAP_TYPE_ns1__localDetails (96)
/* ns1:localDetails */
struct ns1__localDetails
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE_ns1__msgDetails
#define SOAP_TYPE_ns1__msgDetails (94)
/* ns1:msgDetails */
struct ns1__msgDetails
{
	char *contentType;	/* required element of type xsd:string */
	struct ns1__forwardPayload *forward;	/* optional element of type ns1:forwardPayload */
	struct ns1__resCreateContent *createReservation;	/* optional element of type ns1:resCreateContent */
	struct ns1__modifyResContent *modifyReservation;	/* optional element of type ns1:modifyResContent */
	struct ns1__globalReservationId *cancelReservation;	/* optional element of type ns1:globalReservationId */
	struct ns1__globalReservationId *queryReservation;	/* optional element of type ns1:globalReservationId */
	struct ns1__listRequest *listReservations;	/* optional element of type ns1:listRequest */
	struct ns1__createPathContent *createPath;	/* optional element of type ns1:createPathContent */
	struct ns1__refreshPathContent *refreshPath;	/* optional element of type ns1:refreshPathContent */
	struct ns1__teardownPathContent *teardownPath;	/* optional element of type ns1:teardownPathContent */
	struct ns1__forwardReply *forwardResponse;	/* optional element of type ns1:forwardReply */
	struct ns1__createReply *createReservationResponse;	/* optional element of type ns1:createReply */
	struct ns1__modifyResReply *modifyReservationResponse;	/* optional element of type ns1:modifyResReply */
	char *cancelReservationResponse;	/* optional element of type xsd:string */
	struct ns1__resDetails *queryReservationResponse;	/* optional element of type ns1:resDetails */
	struct ns1__listReply *listReservationsResponse;	/* optional element of type ns1:listReply */
	struct ns1__createPathResponseContent *createPathResponse;	/* optional element of type ns1:createPathResponseContent */
	struct ns1__refreshPathResponseContent *refreshPathResponse;	/* optional element of type ns1:refreshPathResponseContent */
	struct ns1__teardownPathResponseContent *teardownPathResponse;	/* optional element of type ns1:teardownPathResponseContent */
};
#endif

#ifndef SOAP_TYPE_ns1__emptyArg
#define SOAP_TYPE_ns1__emptyArg (100)
/* ns1:emptyArg */
struct ns1__emptyArg
{
	char *msg;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__globalReservationId
#define SOAP_TYPE_ns1__globalReservationId (72)
/* ns1:globalReservationId */
struct ns1__globalReservationId
{
	char *gri;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__forward
#define SOAP_TYPE__ns1__forward (101)
/* ns1:forward */
struct _ns1__forward
{
	struct ns1__forwardPayload *payload;	/* required element of type ns1:forwardPayload */
	char *payloadSender;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__AAAFault
#define SOAP_TYPE__ns1__AAAFault (102)
/* ns1:AAAFault */
struct _ns1__AAAFault
{
	char *msg;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__BSSFault
#define SOAP_TYPE__ns1__BSSFault (103)
/* ns1:BSSFault */
struct _ns1__BSSFault
{
	char *msg;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__TopologyFault
#define SOAP_TYPE__ns1__TopologyFault (104)
/* ns1:TopologyFault */
struct _ns1__TopologyFault
{
	char *msg;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__SignalFault
#define SOAP_TYPE__ns1__SignalFault (105)
/* ns1:SignalFault */
struct _ns1__SignalFault
{
	char *msg;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneTopologyContent
#define SOAP_TYPE_ns3__CtrlPlaneTopologyContent (53)
/* ns3:CtrlPlaneTopologyContent */
struct ns3__CtrlPlaneTopologyContent
{
	char *idcId;	/* required element of type xsd:string */
	int __sizepath;	/* sequence of elements <path> */
	struct ns3__CtrlPlanePathContent *path;	/* optional element of type ns3:CtrlPlanePathContent */
	int __sizedomain;	/* sequence of elements <domain> */
	struct ns3__CtrlPlaneDomainContent *domain;	/* optional element of type ns3:CtrlPlaneDomainContent */
	int __sizedomainSignature;	/* sequence of elements <domainSignature> */
	struct ns3__CtrlPlaneDomainSignatureContent *domainSignature;	/* optional element of type ns3:CtrlPlaneDomainSignatureContent */
	char *id;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneDomainContent
#define SOAP_TYPE_ns3__CtrlPlaneDomainContent (106)
/* ns3:CtrlPlaneDomainContent */
struct ns3__CtrlPlaneDomainContent
{
	struct ns3__Lifetime *lifetime;	/* optional element of type ns3:Lifetime */
	int __sizenode;	/* sequence of elements <node> */
	struct ns3__CtrlPlaneNodeContent *node;	/* optional element of type ns3:CtrlPlaneNodeContent */
	int __sizeport;	/* sequence of elements <port> */
	struct ns3__CtrlPlanePortContent *port;	/* optional element of type ns3:CtrlPlanePortContent */
	int __sizelink;	/* sequence of elements <link> */
	struct ns3__CtrlPlaneLinkContent *link;	/* optional element of type ns3:CtrlPlaneLinkContent */
	char *id;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneNodeContent
#define SOAP_TYPE_ns3__CtrlPlaneNodeContent (112)
/* ns3:CtrlPlaneNodeContent */
struct ns3__CtrlPlaneNodeContent
{
	struct ns3__Lifetime *lifetime;	/* optional element of type ns3:Lifetime */
	struct ns3__CtrlPlaneAddressContent *address;	/* optional element of type ns3:CtrlPlaneAddressContent */
	int __sizeport;	/* sequence of elements <port> */
	struct ns3__CtrlPlanePortContent *port;	/* optional element of type ns3:CtrlPlanePortContent */
	char *id;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlanePortContent
#define SOAP_TYPE_ns3__CtrlPlanePortContent (114)
/* ns3:CtrlPlanePortContent */
struct ns3__CtrlPlanePortContent
{
	struct ns3__Lifetime *lifetime;	/* optional element of type ns3:Lifetime */
	char *capacity;	/* optional element of type xsd:string */
	char *maximumReservableCapacity;	/* optional element of type xsd:string */
	char *minimumReservableCapacity;	/* optional element of type xsd:string */
	char *granularity;	/* optional element of type xsd:string */
	char *unreservedCapacity;	/* optional element of type xsd:string */
	int __sizelink;	/* sequence of elements <link> */
	struct ns3__CtrlPlaneLinkContent *link;	/* optional element of type ns3:CtrlPlaneLinkContent */
	char *id;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneLinkContent
#define SOAP_TYPE_ns3__CtrlPlaneLinkContent (116)
/* ns3:CtrlPlaneLinkContent */
struct ns3__CtrlPlaneLinkContent
{
	char *remoteLinkId;	/* optional element of type xsd:string */
	char *trafficEngineeringMetric;	/* required element of type xsd:string */
	char *capacity;	/* optional element of type xsd:string */
	char *maximumReservableCapacity;	/* optional element of type xsd:string */
	char *minimumReservableCapacity;	/* optional element of type xsd:string */
	char *granularity;	/* optional element of type xsd:string */
	char *unreservedCapacity;	/* optional element of type xsd:string */
	int __sizelinkProtectionTypes;	/* sequence of elements <linkProtectionTypes> */
	char **linkProtectionTypes;	/* optional element of type xsd:string */
	int __sizeadministrativeGroups;	/* sequence of elements <administrativeGroups> */
	struct ns3__CtrlPlaneAdministrativeGroup *administrativeGroups;	/* optional element of type ns3:CtrlPlaneAdministrativeGroup */
	struct ns3__CtrlPlaneSwcapContent *SwitchingCapabilityDescriptors;	/* required element of type ns3:CtrlPlaneSwcapContent */
	char *id;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlanePathContent
#define SOAP_TYPE_ns3__CtrlPlanePathContent (85)
/* ns3:CtrlPlanePathContent */
struct ns3__CtrlPlanePathContent
{
	struct ns3__Lifetime *lifetime;	/* optional element of type ns3:Lifetime */
	int __sizehop;	/* sequence of elements <hop> */
	struct ns3__CtrlPlaneHopContent *hop;	/* optional element of type ns3:CtrlPlaneHopContent */
	char *id;	/* required attribute of type xsd:string */
	char *direction;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneHopContent
#define SOAP_TYPE_ns3__CtrlPlaneHopContent (124)
/* ns3:CtrlPlaneHopContent */
struct ns3__CtrlPlaneHopContent
{
	char *domainIdRef;	/* optional element of type xsd:string */
	char *nodeIdRef;	/* optional element of type xsd:string */
	char *portIdRef;	/* optional element of type xsd:string */
	char *linkIdRef;	/* optional element of type xsd:string */
	struct ns3__CtrlPlaneDomainContent *domain;	/* optional element of type ns3:CtrlPlaneDomainContent */
	struct ns3__CtrlPlaneNodeContent *node;	/* optional element of type ns3:CtrlPlaneNodeContent */
	struct ns3__CtrlPlanePortContent *port;	/* optional element of type ns3:CtrlPlanePortContent */
	struct ns3__CtrlPlaneLinkContent *link;	/* optional element of type ns3:CtrlPlaneLinkContent */
	int __sizenextHop;	/* sequence of elements <nextHop> */
	struct ns3__CtrlPlaneNextHopContent *nextHop;	/* optional element of type ns3:CtrlPlaneNextHopContent */
	char *id;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__Lifetime
#define SOAP_TYPE_ns3__Lifetime (110)
/* ns3:Lifetime */
struct ns3__Lifetime
{
	struct ns3__TimeContent *start;	/* optional element of type ns3:TimeContent */
	struct ns3__TimeContent *end;	/* optional element of type ns3:TimeContent */
	struct ns3__Duration *duration;	/* optional element of type ns3:Duration */
	char *id;	/* required attribute of type xsd:string */
	char *direction;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneDomainSignatureContent
#define SOAP_TYPE_ns3__CtrlPlaneDomainSignatureContent (108)
/* ns3:CtrlPlaneDomainSignatureContent */
struct ns3__CtrlPlaneDomainSignatureContent
{
	char *domainId;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneSwcapContent
#define SOAP_TYPE_ns3__CtrlPlaneSwcapContent (122)
/* ns3:CtrlPlaneSwcapContent */
struct ns3__CtrlPlaneSwcapContent
{
	char *switchingcapType;	/* required element of type xsd:string */
	char *encodingType;	/* required element of type xsd:string */
	struct ns3__CtrlPlaneSwitchingCapabilitySpecificInfo *switchingCapabilitySpecificInfo;	/* required element of type ns3:CtrlPlaneSwitchingCapabilitySpecificInfo */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneAdministrativeGroup
#define SOAP_TYPE_ns3__CtrlPlaneAdministrativeGroup (120)
/* ns3:CtrlPlaneAdministrativeGroup */
struct ns3__CtrlPlaneAdministrativeGroup
{
	int group;	/* required element of type xsd:int */
	char *groupID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneSwitchingCapabilitySpecificInfo
#define SOAP_TYPE_ns3__CtrlPlaneSwitchingCapabilitySpecificInfo (132)
/* ns3:CtrlPlaneSwitchingCapabilitySpecificInfo */
struct ns3__CtrlPlaneSwitchingCapabilitySpecificInfo
{
	char *capability;	/* optional element of type xsd:string */
	int *interfaceMTU;	/* optional element of type xsd:int */
	char *vlanRangeAvailability;	/* optional element of type xsd:string */
	char *suggestedVLANRange;	/* optional element of type xsd:string */
	enum xsd__boolean_ *vlanTranslation;	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns4__FilterType
#define SOAP_TYPE_ns4__FilterType (135)
/* ns4:FilterType */
struct ns4__FilterType
{
	int __sizeTopicExpression;	/* sequence of elements <TopicExpression> */
	struct ns4__TopicExpressionType *TopicExpression;	/* optional element of type ns4:TopicExpressionType */
	int __sizeProducerProperties;	/* sequence of elements <ProducerProperties> */
	struct ns4__QueryExpressionType *ProducerProperties;	/* optional element of type ns4:QueryExpressionType */
	int __sizeMessageContent;	/* sequence of elements <MessageContent> */
	struct ns4__QueryExpressionType *MessageContent;	/* optional element of type ns4:QueryExpressionType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE_ns4__SubscriptionPolicyType
#define SOAP_TYPE_ns4__SubscriptionPolicyType (140)
/* ns4:SubscriptionPolicyType */
struct ns4__SubscriptionPolicyType
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE_ns4__NotificationMessageHolderType
#define SOAP_TYPE_ns4__NotificationMessageHolderType (141)
/* ns4:NotificationMessageHolderType */
struct ns4__NotificationMessageHolderType
{
	struct wsa5__EndpointReferenceType *SubscriptionReference;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns4__TopicExpressionType *Topic;	/* optional element of type ns4:TopicExpressionType */
	struct wsa5__EndpointReferenceType *ProducerReference;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns4__MessageType *Message;	/* required element of type ns4:MessageType */
};
#endif

#ifndef SOAP_TYPE_ns4__MessageType
#define SOAP_TYPE_ns4__MessageType (143)
/* ns4:MessageType */
struct ns4__MessageType
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__SubscriptionManagerRP
#define SOAP_TYPE__ns4__SubscriptionManagerRP (145)
/* ns4:SubscriptionManagerRP */
struct _ns4__SubscriptionManagerRP
{
	struct wsa5__EndpointReferenceType ConsumerReference;	/* required element of type wsa5:EndpointReferenceType */
	struct ns4__FilterType *Filter;	/* optional element of type ns4:FilterType */
	struct ns4__SubscriptionPolicyType *SubscriptionPolicy;	/* optional element of type ns4:SubscriptionPolicyType */
	time_t *CreationTime;	/* optional element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__ns4__Notify
#define SOAP_TYPE__ns4__Notify (150)
/* ns4:Notify */
struct _ns4__Notify
{
	int __sizeNotificationMessage;	/* sequence of elements <NotificationMessage> */
	struct ns4__NotificationMessageHolderType *NotificationMessage;	/* required element of type ns4:NotificationMessageHolderType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__UseRaw
#define SOAP_TYPE__ns4__UseRaw (152)
/* ns4:UseRaw */
struct _ns4__UseRaw
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns4__Subscribe_SubscriptionPolicy
#define SOAP_TYPE__ns4__Subscribe_SubscriptionPolicy (154)
/* ns4:Subscribe-SubscriptionPolicy */
struct _ns4__Subscribe_SubscriptionPolicy
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__Subscribe
#define SOAP_TYPE__ns4__Subscribe (153)
/* ns4:Subscribe */
struct _ns4__Subscribe
{
	struct wsa5__EndpointReferenceType ConsumerReference;	/* required element of type wsa5:EndpointReferenceType */
	struct ns4__FilterType *Filter;	/* optional element of type ns4:FilterType */
	char *InitialTerminationTime;	/* optional element of type xsd:string */
	struct _ns4__Subscribe_SubscriptionPolicy *SubscriptionPolicy;	/* optional element of type ns4:Subscribe-SubscriptionPolicy */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__SubscribeResponse
#define SOAP_TYPE__ns4__SubscribeResponse (156)
/* ns4:SubscribeResponse */
struct _ns4__SubscribeResponse
{
	struct wsa5__EndpointReferenceType SubscriptionReference;	/* required element of type wsa5:EndpointReferenceType */
	time_t *CurrentTime;	/* optional element of type xsd:dateTime */
	time_t *TerminationTime;	/* optional element of type xsd:dateTime */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__GetCurrentMessage
#define SOAP_TYPE__ns4__GetCurrentMessage (157)
/* ns4:GetCurrentMessage */
struct _ns4__GetCurrentMessage
{
	struct ns4__TopicExpressionType *Topic;	/* required element of type ns4:TopicExpressionType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__GetCurrentMessageResponse
#define SOAP_TYPE__ns4__GetCurrentMessageResponse (158)
/* ns4:GetCurrentMessageResponse */
struct _ns4__GetCurrentMessageResponse
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__GetMessages
#define SOAP_TYPE__ns4__GetMessages (159)
/* ns4:GetMessages */
struct _ns4__GetMessages
{
	unsigned int *MaximumNumber;	/* optional element of type xsd:unsignedInt */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__GetMessagesResponse
#define SOAP_TYPE__ns4__GetMessagesResponse (162)
/* ns4:GetMessagesResponse */
struct _ns4__GetMessagesResponse
{
	int __sizeNotificationMessage;	/* sequence of elements <NotificationMessage> */
	struct ns4__NotificationMessageHolderType *NotificationMessage;	/* optional element of type ns4:NotificationMessageHolderType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__DestroyPullPoint
#define SOAP_TYPE__ns4__DestroyPullPoint (163)
/* ns4:DestroyPullPoint */
struct _ns4__DestroyPullPoint
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__DestroyPullPointResponse
#define SOAP_TYPE__ns4__DestroyPullPointResponse (164)
/* ns4:DestroyPullPointResponse */
struct _ns4__DestroyPullPointResponse
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__CreatePullPoint
#define SOAP_TYPE__ns4__CreatePullPoint (165)
/* ns4:CreatePullPoint */
struct _ns4__CreatePullPoint
{
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__CreatePullPointResponse
#define SOAP_TYPE__ns4__CreatePullPointResponse (166)
/* ns4:CreatePullPointResponse */
struct _ns4__CreatePullPointResponse
{
	struct wsa5__EndpointReferenceType PullPoint;	/* required element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__Renew
#define SOAP_TYPE__ns4__Renew (167)
/* ns4:Renew */
struct _ns4__Renew
{
	char *TerminationTime;	/* optional element of type xsd:string */
	struct wsa5__EndpointReferenceType SubscriptionReference;	/* required element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__RenewResponse
#define SOAP_TYPE__ns4__RenewResponse (168)
/* ns4:RenewResponse */
struct _ns4__RenewResponse
{
	time_t TerminationTime;	/* required element of type xsd:dateTime */
	time_t *CurrentTime;	/* optional element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *SubscriptionReference;	/* optional element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__Unsubscribe
#define SOAP_TYPE__ns4__Unsubscribe (169)
/* ns4:Unsubscribe */
struct _ns4__Unsubscribe
{
	struct wsa5__EndpointReferenceType SubscriptionReference;	/* required element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__UnsubscribeResponse
#define SOAP_TYPE__ns4__UnsubscribeResponse (170)
/* ns4:UnsubscribeResponse */
struct _ns4__UnsubscribeResponse
{
	struct wsa5__EndpointReferenceType *SubscriptionReference;	/* optional element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__PauseSubscription
#define SOAP_TYPE__ns4__PauseSubscription (171)
/* ns4:PauseSubscription */
struct _ns4__PauseSubscription
{
	struct wsa5__EndpointReferenceType SubscriptionReference;	/* required element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__PauseSubscriptionResponse
#define SOAP_TYPE__ns4__PauseSubscriptionResponse (172)
/* ns4:PauseSubscriptionResponse */
struct _ns4__PauseSubscriptionResponse
{
	struct wsa5__EndpointReferenceType *SubscriptionReference;	/* optional element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__ResumeSubscription
#define SOAP_TYPE__ns4__ResumeSubscription (173)
/* ns4:ResumeSubscription */
struct _ns4__ResumeSubscription
{
	struct wsa5__EndpointReferenceType SubscriptionReference;	/* required element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE__ns4__ResumeSubscriptionResponse
#define SOAP_TYPE__ns4__ResumeSubscriptionResponse (174)
/* ns4:ResumeSubscriptionResponse */
struct _ns4__ResumeSubscriptionResponse
{
	struct wsa5__EndpointReferenceType *SubscriptionReference;	/* optional element of type wsa5:EndpointReferenceType */
	int __size;	/* sequence of elements <-any> */
	char **__any;
};
#endif

#ifndef SOAP_TYPE_ns6__BaseFaultType
#define SOAP_TYPE_ns6__BaseFaultType (175)
/* ns6:BaseFaultType */
struct ns6__BaseFaultType
{
	time_t Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <Description> */
	char **Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns1__vlanTag
#define SOAP_TYPE_ns1__vlanTag (65)
/* Primitive ns1:vlanTag schema type: */
struct ns1__vlanTag
{
	char *__item;
	enum xsd__boolean_ *tagged;	/* optional attribute of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE___ns1__reservationResourceType_sequence
#define SOAP_TYPE___ns1__reservationResourceType_sequence (181)
/* Operation wrapper: */
struct __ns1__reservationResourceType_sequence
{
	struct ns1__localDetails *localDetails;	/* optional element of type ns1:localDetails */
};
#endif

#ifndef SOAP_TYPE_ns1__reservationResourceType
#define SOAP_TYPE_ns1__reservationResourceType (180)
/* ns1:reservationResourceType */
struct ns1__reservationResourceType
{
	char *globalReservationId;	/* optional element of type xsd:string */
	LONG64 startTime;	/* required element of type xsd:long */
	LONG64 endTime;	/* required element of type xsd:long */
	int bandwidth;	/* required element of type xsd:int */
	char *description;	/* required element of type xsd:string */
	struct ns1__pathInfo *pathInfo;	/* required element of type ns1:pathInfo */
	int __size_reservationResourceType_sequence;	/* sequence of elements <-reservationResourceType-sequence> */
	struct __ns1__reservationResourceType_sequence *__reservationResourceType_sequence;
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneNextHopContent
#define SOAP_TYPE_ns3__CtrlPlaneNextHopContent (126)
/* Primitive ns3:CtrlPlaneNextHopContent schema type: */
struct ns3__CtrlPlaneNextHopContent
{
	char *__item;
	int *weight;	/* optional attribute of type xsd:int */
	enum xsd__boolean_ *optional;	/* optional attribute of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns3__TimeContent
#define SOAP_TYPE_ns3__TimeContent (128)
/* Primitive ns3:TimeContent schema type: */
struct ns3__TimeContent
{
	char *__item;
	char *type;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__Duration
#define SOAP_TYPE_ns3__Duration (130)
/* Primitive ns3:Duration schema type: */
struct ns3__Duration
{
	char *__item;
	char *type;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__CtrlPlaneAddressContent
#define SOAP_TYPE_ns3__CtrlPlaneAddressContent (118)
/* Primitive ns3:CtrlPlaneAddressContent schema type: */
struct ns3__CtrlPlaneAddressContent
{
	char *__item;
	char *value;	/* optional attribute of type xsd:string */
	char *type;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__QueryExpressionType
#define SOAP_TYPE_ns4__QueryExpressionType (138)
/* Primitive ns4:QueryExpressionType schema type: */
struct ns4__QueryExpressionType
{
	char *__item;
	char *Dialect;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__TopicExpressionType
#define SOAP_TYPE_ns4__TopicExpressionType (136)
/* ns4:TopicExpressionType */
struct ns4__TopicExpressionType
{
	char *__item;
	char *Dialect;	/* required attribute of type xsd:string */
	char *__mixed;
};
#endif

#ifndef SOAP_TYPE_ns4__SubscribeCreationFailedFaultType
#define SOAP_TYPE_ns4__SubscribeCreationFailedFaultType (183)
/* ns4:SubscribeCreationFailedFaultType */
struct ns4__SubscribeCreationFailedFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__InvalidFilterFaultType
#define SOAP_TYPE_ns4__InvalidFilterFaultType (184)
/* ns4:InvalidFilterFaultType */
struct ns4__InvalidFilterFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
	int __sizeUnknownFilter;	/* sequence of elements <UnknownFilter> */
	char **UnknownFilter;	/* required element of type xsd:QName */
};
#endif

#ifndef SOAP_TYPE_ns4__TopicExpressionDialectUnknownFaultType
#define SOAP_TYPE_ns4__TopicExpressionDialectUnknownFaultType (186)
/* ns4:TopicExpressionDialectUnknownFaultType */
struct ns4__TopicExpressionDialectUnknownFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__InvalidTopicExpressionFaultType
#define SOAP_TYPE_ns4__InvalidTopicExpressionFaultType (187)
/* ns4:InvalidTopicExpressionFaultType */
struct ns4__InvalidTopicExpressionFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__TopicNotSupportedFaultType
#define SOAP_TYPE_ns4__TopicNotSupportedFaultType (188)
/* ns4:TopicNotSupportedFaultType */
struct ns4__TopicNotSupportedFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__MultipleTopicsSpecifiedFaultType
#define SOAP_TYPE_ns4__MultipleTopicsSpecifiedFaultType (189)
/* ns4:MultipleTopicsSpecifiedFaultType */
struct ns4__MultipleTopicsSpecifiedFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__InvalidProducerPropertiesExpressionFaultType
#define SOAP_TYPE_ns4__InvalidProducerPropertiesExpressionFaultType (190)
/* ns4:InvalidProducerPropertiesExpressionFaultType */
struct ns4__InvalidProducerPropertiesExpressionFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__InvalidMessageContentExpressionFaultType
#define SOAP_TYPE_ns4__InvalidMessageContentExpressionFaultType (191)
/* ns4:InvalidMessageContentExpressionFaultType */
struct ns4__InvalidMessageContentExpressionFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__UnrecognizedPolicyRequestFaultType
#define SOAP_TYPE_ns4__UnrecognizedPolicyRequestFaultType (192)
/* ns4:UnrecognizedPolicyRequestFaultType */
struct ns4__UnrecognizedPolicyRequestFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
	int __sizeUnrecognizedPolicy;	/* sequence of elements <UnrecognizedPolicy> */
	char **UnrecognizedPolicy;	/* optional element of type xsd:QName */
};
#endif

#ifndef SOAP_TYPE_ns4__UnsupportedPolicyRequestFaultType
#define SOAP_TYPE_ns4__UnsupportedPolicyRequestFaultType (193)
/* ns4:UnsupportedPolicyRequestFaultType */
struct ns4__UnsupportedPolicyRequestFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
	int __sizeUnsupportedPolicy;	/* sequence of elements <UnsupportedPolicy> */
	char **UnsupportedPolicy;	/* optional element of type xsd:QName */
};
#endif

#ifndef SOAP_TYPE_ns4__NotifyMessageNotSupportedFaultType
#define SOAP_TYPE_ns4__NotifyMessageNotSupportedFaultType (194)
/* ns4:NotifyMessageNotSupportedFaultType */
struct ns4__NotifyMessageNotSupportedFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__UnacceptableInitialTerminationTimeFaultType
#define SOAP_TYPE_ns4__UnacceptableInitialTerminationTimeFaultType (195)
/* ns4:UnacceptableInitialTerminationTimeFaultType */
struct ns4__UnacceptableInitialTerminationTimeFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
	time_t MinimumTime;	/* required element of type xsd:dateTime */
	time_t *MaximumTime;	/* optional element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE_ns4__NoCurrentMessageOnTopicFaultType
#define SOAP_TYPE_ns4__NoCurrentMessageOnTopicFaultType (196)
/* ns4:NoCurrentMessageOnTopicFaultType */
struct ns4__NoCurrentMessageOnTopicFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__UnableToGetMessagesFaultType
#define SOAP_TYPE_ns4__UnableToGetMessagesFaultType (197)
/* ns4:UnableToGetMessagesFaultType */
struct ns4__UnableToGetMessagesFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__UnableToDestroyPullPointFaultType
#define SOAP_TYPE_ns4__UnableToDestroyPullPointFaultType (198)
/* ns4:UnableToDestroyPullPointFaultType */
struct ns4__UnableToDestroyPullPointFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__UnableToCreatePullPointFaultType
#define SOAP_TYPE_ns4__UnableToCreatePullPointFaultType (199)
/* ns4:UnableToCreatePullPointFaultType */
struct ns4__UnableToCreatePullPointFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__UnacceptableTerminationTimeFaultType
#define SOAP_TYPE_ns4__UnacceptableTerminationTimeFaultType (200)
/* ns4:UnacceptableTerminationTimeFaultType */
struct ns4__UnacceptableTerminationTimeFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
	time_t MinimumTime;	/* required element of type xsd:dateTime */
	time_t *MaximumTime;	/* optional element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE_ns4__UnableToDestroySubscriptionFaultType
#define SOAP_TYPE_ns4__UnableToDestroySubscriptionFaultType (201)
/* ns4:UnableToDestroySubscriptionFaultType */
struct ns4__UnableToDestroySubscriptionFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__PauseFailedFaultType
#define SOAP_TYPE_ns4__PauseFailedFaultType (202)
/* ns4:PauseFailedFaultType */
struct ns4__PauseFailedFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns4__ResumeFailedFaultType
#define SOAP_TYPE_ns4__ResumeFailedFaultType (203)
/* ns4:ResumeFailedFaultType */
struct ns4__ResumeFailedFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns5__ResourceUnknownFaultType
#define SOAP_TYPE_ns5__ResourceUnknownFaultType (204)
/* ns5:ResourceUnknownFaultType */
struct ns5__ResourceUnknownFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns5__ResourceUnavailableFaultType
#define SOAP_TYPE_ns5__ResourceUnavailableFaultType (205)
/* ns5:ResourceUnavailableFaultType */
struct ns5__ResourceUnavailableFaultType
{
	time_t ns6__Timestamp;	/* required element of type xsd:dateTime */
	struct wsa5__EndpointReferenceType *ns6__Originator;	/* optional element of type wsa5:EndpointReferenceType */
	struct ns6__ErrorCodeType *ns6__ErrorCode;	/* optional element of type ns6:ErrorCodeType */
	int __sizeDescription;	/* sequence of elements <ns6:Description> */
	char **ns6__Description;	/* optional element of type xsd:string */
	struct ns6__FaultCauseType *ns6__FaultCause;	/* optional element of type ns6:FaultCauseType */
};
#endif

#ifndef SOAP_TYPE_ns6__ErrorCodeType
#define SOAP_TYPE_ns6__ErrorCodeType (176)
/* Primitive ns6:ErrorCodeType schema type: */
struct ns6__ErrorCodeType
{
	char *__item;
	char *dialect;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns6__FaultCauseType
#define SOAP_TYPE_ns6__FaultCauseType (178)
/* Primitive ns6:FaultCauseType schema type: */
struct ns6__FaultCauseType
{
	char *__item;
	char *dialect;	/* optional attribute of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (206)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	struct _ns1__AAAFault *ns1__AAAFault;	/* optional element of type ns1:AAAFault */
	struct _ns1__BSSFault *ns1__BSSFault;	/* optional element of type ns1:BSSFault */
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef SOAP_TYPE___ns1__createReservation
#define SOAP_TYPE___ns1__createReservation (212)
/* Operation wrapper: */
struct __ns1__createReservation
{
	struct ns1__resCreateContent *ns1__createReservation;	/* optional element of type ns1:resCreateContent */
};
#endif

#ifndef SOAP_TYPE___ns1__queryReservation
#define SOAP_TYPE___ns1__queryReservation (214)
/* Operation wrapper: */
struct __ns1__queryReservation
{
	struct ns1__globalReservationId *ns1__queryReservation;	/* optional element of type ns1:globalReservationId */
};
#endif

#ifndef SOAP_TYPE___ns1__listReservations
#define SOAP_TYPE___ns1__listReservations (216)
/* Operation wrapper: */
struct __ns1__listReservations
{
	struct ns1__listRequest *ns1__listReservations;	/* optional element of type ns1:listRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__cancelReservationResponse
#define SOAP_TYPE___ns1__cancelReservationResponse (218)
/* Operation wrapper: */
struct __ns1__cancelReservationResponse
{
	char **ns1__cancelReservationResponse;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE___ns1__cancelReservation
#define SOAP_TYPE___ns1__cancelReservation (219)
/* Operation wrapper: */
struct __ns1__cancelReservation
{
	struct ns1__globalReservationId *ns1__cancelReservation;	/* optional element of type ns1:globalReservationId */
};
#endif

#ifndef SOAP_TYPE___ns1__modifyReservation
#define SOAP_TYPE___ns1__modifyReservation (221)
/* Operation wrapper: */
struct __ns1__modifyReservation
{
	struct ns1__modifyResContent *ns1__modifyReservation;	/* optional element of type ns1:modifyResContent */
};
#endif

#ifndef SOAP_TYPE___ns1__getNetworkTopology
#define SOAP_TYPE___ns1__getNetworkTopology (225)
/* Operation wrapper: */
struct __ns1__getNetworkTopology
{
	struct ns1__getTopologyContent *ns1__getNetworkTopology;	/* optional element of type ns1:getTopologyContent */
};
#endif

#ifndef SOAP_TYPE___ns1__createPath
#define SOAP_TYPE___ns1__createPath (227)
/* Operation wrapper: */
struct __ns1__createPath
{
	struct ns1__createPathContent *ns1__createPath;	/* optional element of type ns1:createPathContent */
};
#endif

#ifndef SOAP_TYPE___ns1__refreshPath
#define SOAP_TYPE___ns1__refreshPath (229)
/* Operation wrapper: */
struct __ns1__refreshPath
{
	struct ns1__refreshPathContent *ns1__refreshPath;	/* optional element of type ns1:refreshPathContent */
};
#endif

#ifndef SOAP_TYPE___ns1__teardownPath
#define SOAP_TYPE___ns1__teardownPath (231)
/* Operation wrapper: */
struct __ns1__teardownPath
{
	struct ns1__teardownPathContent *ns1__teardownPath;	/* optional element of type ns1:teardownPathContent */
};
#endif

#ifndef SOAP_TYPE___ns1__forward
#define SOAP_TYPE___ns1__forward (234)
/* Operation wrapper: */
struct __ns1__forward
{
	struct _ns1__forward *ns1__forward;	/* optional element of type ns1:forward */
};
#endif

#ifndef SOAP_TYPE___ns1__Notify
#define SOAP_TYPE___ns1__Notify (237)
/* Operation wrapper: */
struct __ns1__Notify
{
	struct _ns4__Notify *ns4__Notify;	/* optional element of type ns4:Notify */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (238)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (240)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (241)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_wsa5__RelationshipTypeOpenEnum
#define SOAP_TYPE_wsa5__RelationshipTypeOpenEnum (12)
typedef char *wsa5__RelationshipTypeOpenEnum;
#endif

#ifndef SOAP_TYPE_wsa5__FaultCodesOpenEnumType
#define SOAP_TYPE_wsa5__FaultCodesOpenEnumType (13)
typedef char *wsa5__FaultCodesOpenEnumType;
#endif

#ifndef SOAP_TYPE__wsa5__EndpointReference
#define SOAP_TYPE__wsa5__EndpointReference (19)
typedef struct wsa5__EndpointReferenceType _wsa5__EndpointReference;
#endif

#ifndef SOAP_TYPE__wsa5__ReferenceParameters
#define SOAP_TYPE__wsa5__ReferenceParameters (20)
typedef struct wsa5__ReferenceParametersType _wsa5__ReferenceParameters;
#endif

#ifndef SOAP_TYPE__wsa5__Metadata
#define SOAP_TYPE__wsa5__Metadata (21)
typedef struct wsa5__MetadataType _wsa5__Metadata;
#endif

#ifndef SOAP_TYPE__wsa5__MessageID
#define SOAP_TYPE__wsa5__MessageID (22)
typedef char *_wsa5__MessageID;
#endif

#ifndef SOAP_TYPE__wsa5__RelatesTo
#define SOAP_TYPE__wsa5__RelatesTo (23)
typedef struct wsa5__RelatesToType _wsa5__RelatesTo;
#endif

#ifndef SOAP_TYPE__wsa5__ReplyTo
#define SOAP_TYPE__wsa5__ReplyTo (24)
typedef struct wsa5__EndpointReferenceType _wsa5__ReplyTo;
#endif

#ifndef SOAP_TYPE__wsa5__From
#define SOAP_TYPE__wsa5__From (25)
typedef struct wsa5__EndpointReferenceType _wsa5__From;
#endif

#ifndef SOAP_TYPE__wsa5__FaultTo
#define SOAP_TYPE__wsa5__FaultTo (26)
typedef struct wsa5__EndpointReferenceType _wsa5__FaultTo;
#endif

#ifndef SOAP_TYPE__wsa5__To
#define SOAP_TYPE__wsa5__To (27)
typedef char *_wsa5__To;
#endif

#ifndef SOAP_TYPE__wsa5__Action
#define SOAP_TYPE__wsa5__Action (28)
typedef char *_wsa5__Action;
#endif

#ifndef SOAP_TYPE__wsa5__RetryAfter
#define SOAP_TYPE__wsa5__RetryAfter (30)
typedef ULONG64 _wsa5__RetryAfter;
#endif

#ifndef SOAP_TYPE__wsa5__ProblemHeaderQName
#define SOAP_TYPE__wsa5__ProblemHeaderQName (31)
typedef char *_wsa5__ProblemHeaderQName;
#endif

#ifndef SOAP_TYPE__wsa5__ProblemIRI
#define SOAP_TYPE__wsa5__ProblemIRI (32)
typedef char *_wsa5__ProblemIRI;
#endif

#ifndef SOAP_TYPE__wsa5__ProblemAction
#define SOAP_TYPE__wsa5__ProblemAction (33)
typedef struct wsa5__ProblemActionType _wsa5__ProblemAction;
#endif

#ifndef SOAP_TYPE_ns4__AbsoluteOrRelativeTimeType
#define SOAP_TYPE_ns4__AbsoluteOrRelativeTimeType (41)
typedef char *ns4__AbsoluteOrRelativeTimeType;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createReservation(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__resCreateContent *ns1__createReservation, struct ns1__createReply *ns1__createReservationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryReservation(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__globalReservationId *ns1__queryReservation, struct ns1__resDetails *ns1__queryReservationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__listReservations(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__listRequest *ns1__listReservations, struct ns1__listReply *ns1__listReservationsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__cancelReservation(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__globalReservationId *ns1__cancelReservation, char **ns1__cancelReservationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__modifyReservation(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__modifyResContent *ns1__modifyReservation, struct ns1__modifyResReply *ns1__modifyReservationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getNetworkTopology(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getTopologyContent *ns1__getNetworkTopology, struct ns1__getTopologyResponseContent *ns1__getNetworkTopologyResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__createPathContent *ns1__createPath, struct ns1__createPathResponseContent *ns1__createPathResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__refreshPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__refreshPathContent *ns1__refreshPath, struct ns1__refreshPathResponseContent *ns1__refreshPathResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__teardownPath(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__teardownPathContent *ns1__teardownPath, struct ns1__teardownPathResponseContent *ns1__teardownPathResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__forward(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__forward *ns1__forward, struct ns1__forwardReply *ns1__forwardResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__Notify(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns4__Notify *ns4__Notify);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__Notify(struct soap *soap, struct __ns1__Notify *_param_1);


#ifdef __cplusplus
}
#endif

#endif

/* End of oscarsStub.h */
